name: Shell Commands

on:
  push
    branches: [main]

jobs:
  run-shell-commands:
    runs-on: ubuntu-last
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
